[package]
edition = "2021"
name = "plonk-study"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

ark-bn254 = "0.4"
ark-ff = "0.4"

[dev-dependencies]
